<template>

  <div id="app">
    
   

    <div id="container">

      <div class="inner">

        <header>
          <h1>Vue-countdown</h1>
          <h2></h2>

          <count-down :endtime="time.endtime" :id="time.id" :servertime="time.servertime"></count-down>


        </header>

        <section id="downloads" class="clearfix">
          <a href="https://github.com/andylei18/vue-countdown/zipball/master" id="download-zip" class="button"><span>Download .zip</span></a>
          <a href="https://github.com/andylei18/vue-countdown/tarball/master" id="download-tar-gz" class="button"><span>Download .tar.gz</span></a>
          <a href="https://github.com/andylei18/vue-countdown" id="view-on-github" class="button"><span>View on GitHub</span></a>
        </section>

        <hr>

        <section id="main_content">
          <h3>
<a id="welcome-to-github-pages" class="anchor" href="#welcome-to-github-pages" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Welcome to GitHub Pages.</h3>

<p>This automatic page generator is the easiest way to create beautiful pages for all of your projects. Author your page content here <a href="https://guides.github.com/features/mastering-markdown/">using GitHub Flavored Markdown</a>, select a template crafted by a designer, and publish. After your page is generated, you can check out the new <code>gh-pages</code> branch locally. If you’re using GitHub Desktop, simply sync your repository and you’ll see the new branch.</p>

<h3>
<a id="designer-templates" class="anchor" href="#designer-templates" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Designer Templates</h3>

<p>We’ve crafted some handsome templates for you to use. Go ahead and click 'Continue to layouts' to browse through them. You can easily go back to edit your page before publishing. After publishing your page, you can revisit the page generator and switch to another theme. Your Page content will be preserved.</p>

<h3>
<a id="creating-pages-manually" class="anchor" href="#creating-pages-manually" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Creating pages manually</h3>

<p>If you prefer to not use the automatic generator, push a branch named <code>gh-pages</code> to your repository to create a page manually. In addition to supporting regular HTML content, GitHub Pages support Jekyll, a simple, blog aware static site generator. Jekyll makes it easy to create site-wide headers and footers without having to copy them across every page. It also offers intelligent blog support and other advanced templating features.</p>

<h3>
<a id="authors-and-contributors" class="anchor" href="#authors-and-contributors" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Authors and Contributors</h3>

<p>You can <a href="https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-users-and-teams" class="user-mention">@mention</a> a GitHub username to generate a link to their profile. The resulting <code>&lt;a&gt;</code> element will link to the contributor’s GitHub Profile. For example: In 2007, Chris Wanstrath (<a href="https://github.com/defunkt" class="user-mention">@defunkt</a>), PJ Hyett (<a href="https://github.com/pjhyett" class="user-mention">@pjhyett</a>), and Tom Preston-Werner (<a href="https://github.com/mojombo" class="user-mention">@mojombo</a>) founded GitHub.</p>

<h3>
<a id="support-or-contact" class="anchor" href="#support-or-contact" aria-hidden="true"><span aria-hidden="true" class="octicon octicon-link"></span></a>Support or Contact</h3>

<p>Having trouble with Pages? Check out our <a href="https://help.github.com/pages">documentation</a> or <a href="https://github.com/contact">contact support</a> and we’ll help you sort it out.</p>
        </section>

        <footer>
          Vue-countdown is maintained by <a href="https://github.com/andylei18">andylei18</a><br>
          This page was generated by <a href="https://pages.github.com">GitHub Pages</a>. Tactile theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.
        </footer>

        
      </div>
    </div>
    

  </div>
</template>

<script>
import CountDown from './components/countdown'

export default {
  data () {
    return {
      time:{
        id:'001',
        servertime:'2016/05/18 11:54:59', 
        endtime:'2017/05/25 11:55:00',
      }
    }
  },
  components: {
    CountDown
  },
  // 在创建实例时 `events` 选项简单地调用 `$on`
  events: {
    'callback' (msg) {
      // 事件回调内的 `this` 自动绑定到注册它的实例上
      consle.log('活动时间到了')
    }
  }
}
</script>
<style src="././assets/stylesheets/print.css"></style>
<style src="././assets/stylesheets/github-dark.css"></style>
<style src="././assets/stylesheets/stylesheet.css"></style>
<style type="text/css">
  .ui-app{
    padding: 100px 0;
    color: #303030;
    font-size: 20px;
    font-weight: bold;
  }
</style>
